CREATE DATABASE gnecco
GO

CREATE TABLE InformeInspeccion
(
	Id INT IDENTITY PRIMARY KEY,
	Descripcion TEXT NOT NULL,
	Tipo VARCHAR(50) NOT NULL,
	Nombre VARCHAR(MAX) NOT NULL,
	FechaCreacion DATE NOT NULL
		CONSTRAINT DEFAULT_FECHA_CREACION_INFORME_INSPECCION DEFAULT GETDATE(),
	IndicadorEstado VARCHAR(1) NOT NULL
		CONSTRAINT DEFAULT_INDICADOR_ESTADO_INFORME_INSPECCION DEFAULT 'A',
)
GO

CREATE TABLE GrupoInformeInspeccion
(
	Id INT IDENTITY PRIMARY KEY,
	Descripcion TEXT NOT NULL,
	IndicadorEstado VARCHAR(1) NOT NULL
		CONSTRAINT DEFAULT_INDICADOR_ESTADO_GRUPO_INFORME_INSPECCION DEFAULT 'A',
	InformeInspeccionId INT NOT NULL
		CONSTRAINT FK_INFORME_INSPECCION_X_GRUPO_INFORME_INSPECCION FOREIGN KEY(InformeInspeccionId) REFERENCES InformeInspeccion(Id),
	TipoGrupo VARCHAR(50) NOT NULL
)
GO

ALTER TABLE GrupoInformeInspeccion
ADD GrupoInformeInspeccionId INT NULL
CONSTRAINT FK_GRUPO_INFORME_INSPECCION_X_GRUPO_INFORME_INSPECCION FOREIGN KEY(GrupoInformeInspeccionId)
REFERENCES GrupoInformeInspeccion(Id)
GO


CREATE TABLE DetalleInformeInspeccion
(
	Id INT IDENTITY PRIMARY KEY,
	InformeInspeccionId INT NULL,
		CONSTRAINT FK_INFORME_INSPECCION_X_DETALLE_INFORME_INSPECCION FOREIGN KEY(InformeInspeccionId) REFERENCES InformeInspeccion(Id),
	GrupoInformeInspeccionId INT NULL,
		CONSTRAINT FK_GRUPO_INFORME_X_DETALLE_INFORME_INSPECCION FOREIGN KEY(GrupoInformeInspeccionId) REFERENCES GrupoInformeInspeccion(Id),
	Descripcion TEXT NOT NULL,
	Tipo VARCHAR(50) NOT NULL,
	IndicadorEstado VARCHAR(1) NOT NULL
		CONSTRAINT DEFAULT_INDICADOR_ESTADO_DETALLE_INFORME_INSPECCION DEFAULT 'A',		
)
GO


/*CREATE TABLE DetalleInformeInspeccionVolkswagen
(
	Id INT IDENTITY PRIMARY KEY,
	DetalleInformeInspeccionId INT NOT NULL,
		CONSTRAINT FK_DETALLE_INFORME_INSPECCION_X_DETALLE_INFORME_INSPECCION_VOLKSWAGEN FOREIGN KEY(DetalleInformeInspeccionId) REFERENCES DetalleInformeInspeccion(Id),
	OpcionId INT NOT NULL,
		CONSTRAINT FK_OPCION_X_DETALLE_INFORME_INSPECCION_VOLKSWAGEN FOREIGN KEY(OpcionId) REFERENCES Opcion(Id)
)*/

CREATE TABLE Opcion
(
	Id INT IDENTITY PRIMARY KEY,
	DetalleInformeInspeccionId INT NOT NULL,
		CONSTRAINT FK_DETALLE_INFORME_INSPECCION_X_DETALLE_INFORME_INSPECCION_VOLKSWAGEN FOREIGN KEY(DetalleInformeInspeccionId) REFERENCES DetalleInformeInspeccion(Id),
	Descripcion VARCHAR(100) NOT NULL,
	CodigoAgrupacion INT NOT NULL,
	IndicadorEstado VARCHAR(1) NOT NULL
		CONSTRAINT DEFAULT_INDICADOR_ESTADO_OPCION DEFAULT 'A',
)
GO

CREATE TABLE InformeInspeccionCompleto
(
	Id INT IDENTITY PRIMARY KEY,
	InformeInspeccionId INT NOT NULL,
		CONSTRAINT FK_INFORME_INSPECCION_X_INFORME_INSPECCION_COMPLETO FOREIGN KEY(InformeInspeccionId) REFERENCES InformeInspeccion(Id),
	Fecha DATETIME NOT NULL
		CONSTRAINT DEFAULT_FECHA_INFORME_INSPECCION_COMPLETO DEFAULT GETDATE(),
	IndicadorEstado VARCHAR(1) NOT NULL
		CONSTRAINT DEFAULT_INDICADOR_ESTADO_INFORME_INSPECCION_COMPLETO DEFAULT 'A',	
	Tipo VARCHAR(50) NOT NULL
)
GO


CREATE TABLE InformeInspeccionNissanCompleto
(
	Id INT NOT NULL PRIMARY KEY,
		CONSTRAINT FK_INFORME_INSPECCION_COMPLETO_X_INFORME_INSPECCION_NISSAN_COMPLETO FOREIGN KEY(Id) REFERENCES InformeInspeccionCompleto(Id),
	Preventivo INT NOT NULL,
	Correctivo INT NOT NULL,
	Kms VARCHAR(MAX) NOT NULL,
	NumeroOT VARCHAR(MAX) NOT NULL,
	Cliente VARCHAR(MAX) NOT NULL,
	Tecnico VARCHAR(MAX) NOT NULL,
	Placa VARCHAR(MAX) NOT NULL,
	ResultadosMantenimiento VARCHAR(MAX) NOT NULL,
)
GO


CREATE TABLE InformeInspeccionVolkswagenCompleto
(
	Id INT NOT NULL PRIMARY KEY,
		CONSTRAINT FK_INFORME_INSPECCION_COMPLETO_X_INFORME_INSPECCION_VOLKSWAGEN_COMPLETO FOREIGN KEY(Id) REFERENCES InformeInspeccionCompleto(Id),
	Comentarios VARCHAR(MAX) NULL,
	Km VARCHAR(40) NOT NULL,
	LetraDistribucionMotor VARCHAR(40) NOT NULL,
	NombreTecnico VARCHAR(MAX) NOT NULL,
	Orden VARCHAR(100) NOT NULL,
	Placa VARCHAR(20) NOT NULL,
	Vin VARCHAR(MAX) NOT NULL,
	IntervaloKilometros VARCHAR(MAX) NOT NULL
)
GO

CREATE TABLE GrupoInformeInspeccionCompleto
(
	Id INT IDENTITY PRIMARY KEY,
	Tipo VARCHAR(50) NOT NULL,
	InformeInspeccionCompletoId INT NOT NULL
		CONSTRAINT FK_INFORME_INSPECCION_COMPLETO_X_GRUPO_INFORME_INSPECCION_COMPLETO FOREIGN KEY(InformeInspeccionCompletoId) REFERENCES InformeInspeccionCompleto(Id),
	GrupoInformeInspeccionId INT NOT NULL
		CONSTRAINT FK_GRUPO_INFORME_INSPECCION_X_GRUPO_INFORME_INSPECCION_COMPLETO FOREIGN KEY(GrupoInformeInspeccionId) References GrupoInformeInspeccion(Id)
)
GO

CREATE TABLE DetalleInformeInspeccionCompleto
(
	Id INT IDENTITY PRIMARY KEY,
	InformeInspeccionCompletoId INT NULL
		CONSTRAINT FK_INFORME_INSPECCION_COMPLETO_X_DETALLE_INFORME_INSPECCION_COMPLETO FOREIGN KEY(InformeInspeccionCompletoId) REFERENCES InformeInspeccionCompleto(Id),
	GrupoInformeInspeccionCompletoId INT NULL
		CONSTRAINT FK_GRUPO_INFORME_INSPECCION_COMPLETO_X_DETALLE_INFORME_INSPECCION_COMPLETO FOREIGN KEY(GrupoInformeInspeccionCompletoId) REFERENCES GrupoInformeInspeccionCompleto(Id),
	DetalleInformeInspeccionId INT NOT NULL
		CONSTRAINT FK_DETALLE_INFORME_INSPECCION_X_DETALLE_INFORME_INSPECCION_COMPLETO FOREIGN KEY(DetalleInformeInspeccionId) REFERENCES DetalleInformeInspeccion(Id),
	Tipo VARCHAR(50) NOT NULL
)
GO


CREATE TABLE ValorOpcion
(
	Id INT IDENTITY PRIMARY KEY,
	DetalleInformeInspeccionCompletoId INT NOT NULL
		CONSTRAINT FK_DETALLE_INFORME_INSPECCION_COMPLETO_X_VALOR_OPCION FOREIGN KEY(DetalleInformeInspeccionCompletoId) REFERENCES DetalleInformeInspeccionCompleto(Id),
	OpcionId INT NOT NULL
		CONSTRAINT FK_OPCION_X_VALOR_OPCION FOREIGN KEY(OpcionId) REFERENCES Opcion(Id),
	Valor VARCHAR(MAX) NOT NULL
)

CREATE TABLE InformeInspeccionFordCompleto
(
	Id INT NOT NULL PRIMARY KEY,
		CONSTRAINT FK_INFORME_INSPECCION_COMPLETO_X_INFORME_INSPECCION_FORD_COMPLETO FOREIGN KEY(Id) REFERENCES InformeInspeccionCompleto(Id),
	NombreCliente VARCHAR(100) NOT NULL,
	CorreoCliente VARCHAR(100) NOT NULL,
	Comentarios VARCHAR(MAX) NOT NULL,
	AsesorServicio VARCHAR(50) NOT NULL,
	RoTag VARCHAR(50) NOT NULL,
	MesInspeccionEstatal VARCHAR(50) NOT NULL,
	Tecnico VARCHAR(50) NOT NULL,
	Marca VARCHAR(50) NOT NULL,
	Modelo VARCHAR(50) NOT NULL,
	Anio INT NOT NULL,
	Millaje VARCHAR(50) NOT NULL,
	Vin VARCHAR(50) NOT NULL,
	Placa VARCHAR(50) NOT NULL
)
GO

CREATE TABLE Inventario
(
	Id INT IDENTITY PRIMARY KEY,
	FechaRecepcion DATETIME NOT NULL,
	HoraRecepcion DATETIME NOT NULL,
	Placa VARCHAR(MAX) NOT NULL,
	KilometrajeLlegada VARCHAR(MAX) NOT NULL,
	FechaPrometida DATETIME NOT NULL,
	HoraPrometida DATETIME NOT NULL,
	FacturarA VARCHAR(MAX) NOT NULL,
	Ruc VARCHAR(MAX) NOT NULL,
	Propietario VARCHAR(MAX) NOT NULL,
	BoletaFactura BIT DEFAULT 1,
	Direccion VARCHAR(MAX) NOT NULL,
	TelefonoMovil VARCHAR(MAX) NOT NULL,
	CorreoElectronico VARCHAR(MAX) NOT NULL,
	Dni VARCHAR(8) NOT NULL,
	ManifestoCLiente TEXT NOT NULL,
	RutaFirma VARCHAR(MAX) NOT NULL,
	Cenicero BIT DEFAULT 1,
	Encendedor BIT DEFAULT 1,
	Radio BIT DEFAULT 1,
	MascaraRadio BIT DEFAULT 1,
	Antena BIT DEFAULT 1,
	TarjetaPropiedad BIT DEFAULT 1,
	Soat BIT DEFAULT 1,
	SeguroRueda BIT DEFAULT 1,
	VasosRueda BIT DEFAULT 1,
	LucesBajas BIT DEFAULT 1,
	TapaSol BIT DEFAULT 1,
	PlumillasDuchas BIT DEFAULT 1,
	Escapines BIT DEFAULT 1,
	EmblMascara BIT DEFAULT 1,
	TapaAceite BIT DEFAULT 1,
	TapaTanqueComb BIT DEFAULT 1,
	TapaRadiador BIT DEFAULT 1,
	TapaDepRefrg BIT DEFAULT 1,
	TapaDepLiqFren BIT DEFAULT 1,
	LlantaRepuesto BIT DEFAULT 1,
	LucesAltas BIT DEFAULT 1,
	Neblineros BIT DEFAULT 1,
	Claxon BIT DEFAULT 1,
	Espejos BIT DEFAULT 1,
	PisosJebeAlfombra BIT DEFAULT 1,
	CorteCorriente BIT DEFAULT 1,
	LunasElectricasDelt BIT DEFAULT 1,
	LunasElectricasPost BIT DEFAULT 1,
	SistVentilador BIT DEFAULT 1,
	Tacometro BIT DEFAULT 1,
	GataPalanca BIT DEFAULT 1,
	LlaveRueda BIT DEFAULT 1,
	EmblMaletera BIT DEFAULT 1,
	Herramientas BIT DEFAULT 1,
	CajaCd BIT DEFAULT 1,
	Botiquin BIT DEFAULT 1,
	Extintor BIT DEFAULT 1,
	Triangulo BIT DEFAULT 1,
	CableBateria BIT DEFAULT 1,
	CableRemolque BIT DEFAULT 1,
	ObjetosValor BIT DEFAULT 1,
	VehiculoSucioRayaduras BIT DEFAULT 1,
	Asesor VARCHAR(MAX) NOT NULL,
	Observaciones TEXT NOT NULL,
)

CREATE TABLE CoordenadasInventario
(
	Id INT IDENTITY PRIMARY KEY,
	InventarioId INT NOT NULL
		CONSTRAINT FK_INVENTARIO_X_COORDENADAS_INVENTARIO FOREIGN KEY(InventarioId) REFERENCES Inventario(Id),
	PointLeft DECIMAL NOT NULL,
	PointTop DECIMAL NOT NULL,
	PointRight DECIMAL NOT NULL,
	PointBottom DECIMAL NOT NULL,
	Orden INT NOT NULL,
	EstadoAutoparte VARCHAR(MAX) NOT NULL,
	Comentario VARCHAR(MAX) NOT NULL
)

CREATE TABLE InventarioFoto(
	Id INT IDENTITY PRIMARY KEY,
	Ruta VARCHAR(MAX) NOT NULL,
	InventarioId INT NOT NULL 
		CONSTRAINT FK_INVENTARIO_FOTO_X_INVENTARIO FOREIGN KEY(InventarioId) REFERENCES Inventario(Id),
)
